runtime: nodejs12
instance_class: F1

automatic_scaling:
  min_instances: 0

default_expiration: 1m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto